// This file was generated by lezer-generator. You probably shouldn't edit it.
import {LRParser} from "@lezer/lr"
export const parser = LRParser.deserialize({
  version: 14,
  states: "!QQYQPOOOOQO'#Cg'#CgOOQO'#Ch'#ChOOQO'#Cj'#CjOOQO'#C`'#C`OOQO'#Cl'#ClQYQPOOOOQO-E6j-E6j",
  stateData: "$O~OPOSQOS~OTSOUSOVSOWSOXSOYSO]QO_SOcPOdPOePOfPOgPOhPOiPOjPOkPOlPOmPOnPOoQOpQOqQOrQOsQOtQOuQOvQOwQOxQOyQOzQO{QO|RO}RO!ORO!PRO!QRO!RRO!SRO!TRO!URO~O",
  goto: "paPPPPbPPPPPPffPfPjTTOUTSOUQUORVU",
  nodeNames: "⚠ WS Newline Program Token Identifier PascalCaseIdentifier Wildcard Number Text LineComment KeywordToken OperatorToken Minus PunctuationToken CallEmpty",
  maxTerm: 52,
  skippedNodes: [0,1,2],
  repeatNodeCount: 1,
  tokenData: "3t~RzXY#uYZ$T]^#upq#uuv$Ywx$_xy&Ryz&`z{&e{|&j|}&o}!O&t!O!P'}!P!Q(S!Q![(X![!](r!^!_(w!_!`)U!`!a)q!c!d*O!d!e*m!e!h*O!h!i+e!i!n*O!n!o,o!o!p.a!p!r*O!r!s.{!s!u*O!u!v/{!v!w0m!w!y*O!y!z1_!z!}*O!}#O2e#P#Q2j#Q#R2o#R#S2t#T#o3P#o#p3_#p#q3d#q#r3o~#zRP~XY#u]^#upq#u~$YOQ~~$_Oz~~$bWOY$_Zw$_wx$zx#O$_#O#P%P#P;'S$_;'S;=`%{<%lO$_~%POX~~%SRO;'S$_;'S;=`%];=`O$_~%`XOY$_Zw$_wx$zx#O$_#O#P%P#P;'S$_;'S;=`%{;=`<%l$_<%lO$_~&OP;=`<%l$_~&WP!P~yz&Z~&`O_~~&eO!Q~~&jOx~~&oOw~~&tO}~~&wUOt'Zu}'Z}!O'`!O;'S'Z;'S;=`'w<%lO'Z~'`O]~~'eSY~OY'`Z;'S'`;'S;=`'q<%lO'`~'tP;=`<%l'`~'zP;=`<%l'Z~(SO!O~~(XOy~~(^QW~!O!P(d!Q![(X~(gP!Q![(j~(oPW~!Q![(j~(wO|~~(|Pu~!_!`)P~)UOs~~)ZQv~!P!Q)a!`!a)l~)dP!_!`)g~)lOq~~)qOp~~)vPt~!_!`)y~*OOr~~*RR!Q![*[#R#S*[#T#o*[~*aSU~!Q![*[!c!}*[#R#S*[#T#o*[~*pS!Q![*[!n!o*|#R#S*[#T#o*[~+PP!q!r+S~+VP!e!f+Y~+]P!m!n+`~+eOl~~+hS!Q![*[!w!x+t#R#S*[#T#o*[~+wP!p!q+z~+}P!e!f,Q~,TP!v!w,W~,ZP!k!l,^~,aP!q!r,d~,gP!p!q,j~,oOe~~,rT!Q![*[!c!d-R!k!l-p#R#S*[#T#o*[~-UP!v!w-X~-[P!g!h-_~-bP!u!v-e~-hP!v!w-k~-pOg~~-sQ!p!q-y!u!v.U~-|P!m!n.P~.UOf~~.XP!v!w.[~.aOc~~.dS!Q![*[!c!d.p#R#S*[#T#o*[~.sP!r!s.v~.{Od~~/OS!Q![*[!c!d/[#R#S*[#T#o*[~/_P!u!v/b~/eP!u!v/h~/mPm~!g!h/p~/sP!f!g/v~/{On~~0OS!Q![*[!m!n0[#R#S*[#T#o*[~0_P!k!l0b~0eP!r!s0h~0mOk~~0pS!Q![*[!j!k0|#R#S*[#T#o*[~1PP!g!h1S~1VP!p!q1Y~1_Oh~~1bS!Q![*[!j!k1n#R#S*[#T#o*[~1qQ!g!h1w!k!l2S~1zP!p!q1}~2SOi~~2VP!n!o2Y~2]P!g!h2`~2eOj~~2jO!T~~2oO!U~~2tO{~~2wP#R#S2z~3POV~~3URT~!Q![3P#R#S3P#T#o3P~3dO!R~~3gP!`!a3j~3oOo~~3tO!S~",
  tokenizers: [0],
  topRules: {"Program":[0,3]},
  tokenPrec: 0
})
