// This file was generated by lezer-generator. You probably shouldn't edit it.
export const
  WS = 1,
  Newline = 2,
  Program = 3,
  Token = 4,
  Identifier = 5,
  PascalCaseIdentifier = 6,
  Wildcard = 7,
  Number = 8,
  Text = 9,
  LineComment = 10,
  KeywordToken = 11,
  OperatorToken = 12,
  Minus = 13,
  PunctuationToken = 14,
  CallEmpty = 15
