FROM rust:1
WORKDIR /app

RUN rustup target add wasm32-unknown-unknown
RUN --mount=type=cache,target=/usr/local/cargo,from=rust,source=/usr/local/cargo \
    cargo install mzoon --git https://github.com/MoonZoon/MoonZoon --rev 19c6cf6b4d07cd27bee7758977ef1ea4d5b9933d --locked

COPY . .

RUN --mount=type=cache,target=/usr/local/cargo,from=rust,source=/usr/local/cargo \
    --mount=type=cache,target=target \
    /usr/local/cargo/bin/mzoon build

RUN --mount=type=cache,target=target \
    ["cp", "./target/debug/backend", "/usr/local/bin/moon_app"]

ENTRYPOINT ["moon_app"]
